import { sql } from "drizzle-orm";
import { boolean, doublePrecision, index, integer, pgTable, serial, text } from "drizzle-orm/pg-core";

export const inventoryLots = pgTable(
  "inventory_lots",
  {
    id: serial("id").primaryKey(),
    organizationCode: text("organization_code").notNull().default("USA"),
    receivedDate: text("received_date").notNull(),
    loadDate: text("load_date"),
    supplier: text("supplier"),
    warehouse: text("warehouse").notNull(),
    pickupNumber: text("pickup_number"),
    product: text("product").notNull(),
    presentation: text("presentation"),
    size: text("size"),
    label: text("label"),
    totalBoxes: integer("total_boxes").notNull(),
    boxesPerPallet: integer("boxes_per_pallet"),
    palletsPerLoad: integer("pallets_per_load"),
    availableBoxes: integer("available_boxes").notNull(),
    unitCost: doublePrecision("unit_cost"),
    purchasePrice: doublePrecision("purchase_price"),
    freightCost: doublePrecision("freight_cost").notNull().default(0),
    mexicoCustomsCost: doublePrecision("mexico_customs_cost").notNull().default(0),
    usCustomsCost: doublePrecision("us_customs_cost").notNull().default(0),
    overweightCost: doublePrecision("overweight_cost").notNull().default(0),
    redLightCost: doublePrecision("red_light_cost").notNull().default(0),
    coldStorage: text("cold_storage"),
    coldStorageCost: doublePrecision("cold_storage_cost").notNull().default(0),
    additionalExpenses: text("additional_expenses").notNull().default("[]"),
    attachments: text("attachments").notNull().default("[]"),
    costAttachments: text("cost_attachments").notNull().default("{}"),
    costCurrencies: text("cost_currencies").notNull().default("{}"),
    exchangeRate: doublePrecision("exchange_rate"),
    totalImportCost: doublePrecision("total_import_cost"),
    createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP::text`),
  },
  (table) => [
    index("inventory_org_product_idx").on(table.organizationCode, table.product),
    index("inventory_org_available_idx").on(table.organizationCode, table.availableBoxes),
  ],
);

export const coldStorages = pgTable(
  "cold_storages",
  {
    id: serial("id").primaryKey(),
    organizationCode: text("organization_code").notNull().default("USA"),
    name: text("name").notNull(),
    address: text("address").notNull(),
    phone: text("phone").notNull(),
    stateCode: text("state_code").notNull().default(""),
    stateName: text("state_name").notNull().default(""),
    city: text("city").notNull().default(""),
    street: text("street").notNull().default(""),
    exteriorNumber: text("exterior_number").notNull().default(""),
    interiorNumber: text("interior_number"),
    postalCode: text("postal_code").notNull().default(""),
    createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP::text`),
  },
  (table) => [index("cold_storage_org_name_idx").on(table.organizationCode, table.name)],
);

export const products = pgTable(
  "products",
  {
    id: serial("id").primaryKey(),
    organizationCode: text("organization_code").notNull().default("USA"),
    name: text("name").notNull(),
    alias: text("alias").notNull().default(""),
    presentation: text("presentation"),
    size: text("size"),
    label: text("label"),
    boxesPerPallet: integer("boxes_per_pallet"),
    createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP::text`),
  },
  (table) => [index("products_org_name_idx").on(table.organizationCode, table.name)],
);

export const sales = pgTable(
  "sales",
  {
    id: serial("id").primaryKey(),
    organizationCode: text("organization_code").notNull().default("USA"),
    operationType: text("operation_type").notNull().default("DIRECT_RESALE"),
    supplier: text("supplier"),
    inventoryLotId: integer("inventory_lot_id").references(() => inventoryLots.id),
    saleDate: text("sale_date").notNull(),
    customer: text("customer").notNull(),
    sellerName: text("seller_name"),
    purchaseOrder: text("purchase_order"),
    warehouse: text("warehouse").notNull(),
    pickupNumber: text("pickup_number").notNull(),
    boxes: integer("boxes").notNull(),
    product: text("product").notNull(),
    presentation: text("presentation"),
    size: text("size"),
    label: text("label"),
    purchasePrice: doublePrecision("purchase_price"),
    salePrice: doublePrecision("sale_price"),
    profit: doublePrecision("profit"),
    shipDate: text("ship_date"),
    shipTo: text("ship_to"),
    pickupDate: text("pickup_date"),
    total: doublePrecision("total"),
    dueDate: text("due_date"),
    loadStatus: text("load_status").notNull().default("OK"),
    statusUpdatedAt: text("status_updated_at"),
    pasReviewDays: integer("pas_review_days"),
    pasReviewDueDate: text("pas_review_due_date"),
    usdaInspectionStatus: text("usda_inspection_status"),
    usdaInspectionObjectKey: text("usda_inspection_object_key"),
    usdaInspectionFileName: text("usda_inspection_file_name"),
    usdaInspectionContentType: text("usda_inspection_content_type"),
    usdaInspectionUploadedAt: text("usda_inspection_uploaded_at"),
    paymentStatus: text("payment_status").notNull().default("PENDIENTE"),
    invoiceNumber: text("invoice_number"),
    invoiceItems: text("invoice_items"),
    originalInvoiceItems: text("original_invoice_items"),
    invoiceAdjustments: text("invoice_adjustments").notNull().default("[]"),
    bolObjectKey: text("bol_object_key"),
    bolFileName: text("bol_file_name"),
    bolContentType: text("bol_content_type"),
    bolUploadedAt: text("bol_uploaded_at"),
    canceledAt: text("canceled_at"),
    canceledBy: text("canceled_by"),
    cancellationReason: text("cancellation_reason"),
    cancellationDetail: text("cancellation_detail"),
    createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP::text`),
  },
  (table) => [
    index("sales_org_date_idx").on(table.organizationCode, table.saleDate),
    index("sales_org_pickup_idx").on(table.organizationCode, table.pickupNumber),
  ],
);

export const businessPartners = pgTable(
  "business_partners",
  {
    id: serial("id").primaryKey(),
    organizationCode: text("organization_code").notNull().default("USA"),
    partnerType: text("partner_type").notNull(),
    name: text("name").notNull(),
    pacaNumber: text("paca_number").notNull().default(""),
    taxId: text("tax_id").notNull(),
    blueBookNumber: text("blue_book_number").notNull(),
    dunsNumber: text("duns_number").notNull(),
    street: text("street").notNull(),
    exteriorNumber: text("exterior_number").notNull(),
    interiorNumber: text("interior_number"),
    stateCode: text("state_code").notNull(),
    stateName: text("state_name").notNull(),
    city: text("city").notNull(),
    postalCode: text("postal_code").notNull(),
    contactName: text("contact_name").notNull(),
    contactEmail: text("contact_email").notNull(),
    contactPhone: text("contact_phone").notNull(),
    buyerName: text("buyer_name").notNull().default(""),
    buyerEmail: text("buyer_email").notNull().default(""),
    buyerOfficePhone: text("buyer_office_phone").notNull().default(""),
    buyerOfficeExtension: text("buyer_office_extension").notNull().default(""),
    buyerMobilePhone: text("buyer_mobile_phone").notNull().default(""),
    assignedSeller: text("assigned_seller"),
    profitPercentage: doublePrecision("profit_percentage").notNull().default(0),
    createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP::text`),
  },
  (table) => [
    index("partners_org_type_name_idx").on(table.organizationCode, table.partnerType, table.name),
    index("partners_org_tax_id_idx").on(table.organizationCode, table.taxId),
  ],
);

export const companySettings = pgTable("company_settings", {
  id: integer("id").primaryKey().default(1),
  organizationCode: text("organization_code").notNull().default("USA"),
  legalName: text("legal_name").notNull().default("NORWEST PRODUCE LLC"),
  street: text("street").notNull().default("710 LAUREL AVENUE"),
  city: text("city").notNull().default("MCALLEN"),
  state: text("state").notNull().default("TX"),
  postalCode: text("postal_code").notNull().default("78501"),
  blueBookNumber: text("blue_book_number").notNull().default(""),
  pacaNumber: text("paca_number").notNull().default(""),
  dunsNumber: text("duns_number").notNull().default(""),
  taxId: text("tax_id").notNull().default(""),
  norwestProfitPercentage: doublePrecision("norwest_profit_percentage").notNull().default(16),
  updatedAt: text("updated_at").notNull().default(sql`CURRENT_TIMESTAMP::text`),
});

export const userAccounts = pgTable(
  "user_accounts",
  {
    id: serial("id").primaryKey(),
    organizationCode: text("organization_code").notNull().default("USA"),
    fullName: text("full_name").notNull(),
    alias: text("alias").notNull(),
    email: text("email").notNull(),
    passwordHash: text("password_hash").notNull(),
    permissions: text("permissions").notNull().default("[]"),
    profitPercentage: doublePrecision("profit_percentage").notNull().default(0),
    active: boolean("active").notNull().default(true),
    createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP::text`),
  },
  (table) => [
    index("users_org_alias_idx").on(table.organizationCode, table.alias),
    index("users_org_email_idx").on(table.organizationCode, table.email),
  ],
);
