import { sql } from "drizzle-orm";
import { index, integer, real, sqliteTable, text } from "drizzle-orm/sqlite-core";

export const inventoryLots = sqliteTable(
  "inventory_lots",
  {
    id: integer("id").primaryKey({ autoIncrement: true }),
    organizationCode: text("organization_code").notNull().default("USA"),
    receivedDate: text("received_date").notNull(),
    supplier: text("supplier"),
    warehouse: text("warehouse").notNull(),
    pickupNumber: text("pickup_number"),
    product: text("product").notNull(),
    presentation: text("presentation"),
    size: text("size"),
    label: text("label"),
    totalBoxes: integer("total_boxes").notNull(),
    availableBoxes: integer("available_boxes").notNull(),
    unitCost: real("unit_cost"),
    createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`),
  },
  (table) => [
    index("inventory_org_product_idx").on(table.organizationCode, table.product),
    index("inventory_org_available_idx").on(table.organizationCode, table.availableBoxes),
  ],
);

export const sales = sqliteTable(
  "sales",
  {
    id: integer("id").primaryKey({ autoIncrement: true }),
    organizationCode: text("organization_code").notNull().default("USA"),
    operationType: text("operation_type").notNull().default("DIRECT_RESALE"),
    supplier: text("supplier"),
    inventoryLotId: integer("inventory_lot_id").references(() => inventoryLots.id),
    saleDate: text("sale_date").notNull(),
    customer: text("customer").notNull(),
    purchaseOrder: text("purchase_order"),
    warehouse: text("warehouse").notNull(),
    pickupNumber: text("pickup_number").notNull(),
    boxes: integer("boxes").notNull(),
    product: text("product").notNull(),
    presentation: text("presentation"),
    size: text("size"),
    label: text("label"),
    purchasePrice: real("purchase_price"),
    salePrice: real("sale_price"),
    profit: real("profit"),
    shipDate: text("ship_date"),
    pickupDate: text("pickup_date"),
    total: real("total"),
    dueDate: text("due_date"),
    loadStatus: text("load_status").notNull().default("OK"),
    paymentStatus: text("payment_status").notNull().default("PENDIENTE"),
    invoiceNumber: text("invoice_number"),
    createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`),
  },
  (table) => [
    index("sales_org_date_idx").on(table.organizationCode, table.saleDate),
    index("sales_org_pickup_idx").on(table.organizationCode, table.pickupNumber),
  ],
);

export const businessPartners = sqliteTable(
  "business_partners",
  {
    id: integer("id").primaryKey({ autoIncrement: true }),
    organizationCode: text("organization_code").notNull().default("USA"),
    partnerType: text("partner_type").notNull(),
    name: text("name").notNull(),
    taxId: text("tax_id").notNull(),
    blueBookNumber: text("blue_book_number").notNull(),
    dunsNumber: text("duns_number").notNull(),
    street: text("street").notNull(),
    exteriorNumber: text("exterior_number").notNull(),
    interiorNumber: text("interior_number"),
    stateCode: text("state_code").notNull(),
    stateName: text("state_name").notNull(),
    city: text("city").notNull(),
    postalCode: text("postal_code").notNull(),
    contactName: text("contact_name").notNull(),
    contactEmail: text("contact_email").notNull(),
    contactPhone: text("contact_phone").notNull(),
    createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`),
  },
  (table) => [
    index("partners_org_type_name_idx").on(table.organizationCode, table.partnerType, table.name),
    index("partners_org_tax_id_idx").on(table.organizationCode, table.taxId),
  ],
);
